when:
  - event: push
    branch: main
  - event: pull_request

labels:
  backend: docker

steps:
  - name: checks
    image: nixos/nix:2.34.8
    commands:
      - nix profile add nixpkgs#devenv
      - devenv shell -- fmt-check
      - devenv shell -- unit-test
      - devenv shell -- clippy
